name: Build and Deploy Games

on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/pygbag.yml"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  find-games:
    runs-on: ubuntu-latest
    outputs:
      game_folders: ${{ steps.find-folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v2
      - id: find-folders
        run: |
          folders=$(find . -type f -name "main.py" -printf "%h\n" | jq -R -s -c 'split("\n")[:-1]')
          echo "folders=$folders" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: find-games
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game_folder: ${{ fromJson(needs.find-games.outputs.game_folders) }}
    env:
      GAME_NAME: ${{ matrix.game_folder }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install pygbag
        run: pip install pygbag
      - name: Build ${{ env.GAME_NAME }}
        run: python -m pygbag --build $GITHUB_WORKSPACE/${{ env.GAME_NAME }}/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.GAME_NAME }}-build
          path: build/web
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/web
          target-folder: ${{ env.GAME_NAME }}
