name: snake
on:
  push:
    branches: [main]
    paths:
      - "*.py"
      - ".github/workflows/pygbag.yml"
  pull_request:
    branches: [main]
    paths:
      - "*.py"
      - ".github/workflows/pygbag.yml"
  workflow_dispatch:

jobs:
  build-pygbag:
    env:
      GAME: snake
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          python -m pip install pygbag
          python -m pygbag --build $GITHUB_WORKSPACE/${{ env.GAME }}/main.py
      - name: "Upload to GitHub pages branch gh-pages"
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/web
          target-folder: ${{ env.GAME }}
