name: Build and Deploy Snake Game

on:
  push:
    branches: [main]
    paths:
      - "snake/**"
      - ".github/workflows/pygbag.yml"
  pull_request:
    branches: [main]
    paths:
      - "snake/**"
      - ".github/workflows/pygbag.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    env:
      GAME: snake
    name: Build and Deploy for Emscripten pygbag runtime
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          python -m pip install pygbag
          python -m pygbag --build $GITHUB_WORKSPACE/${{ env.GAME }}/main.py

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "${{ env.GAME }}/build/web"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
